#ifndef _LMGENL_H_
#define _LMGENL_H_

enum lmgenl_commands
{
	LMGENL_CMD_UNSPEC = 0,

	LMGENL_CMD_STATUS,
	LMGENL_CMD_PADQ_RQST,
	LMGENL_CMD_PADQ,

	__LMGENL_CMD_MAX,
};
#define LMGENL_CMD_MAX (__LMGENL_CMD_MAX - 1)


enum lmgenl_attrs
{
	LM_GENL_STS_ATTR_UNSPEC = 0,

	LMGENL_ATTR_ACMACADDR,
	LMGENL_ATTR_HOSTMACADDR,
	LMGENL_ATTR_SESSIONID,

	LMGENL_ATTR_IFINDEX,
	LMGENL_ATTR_REMOTEV6LLADDR,
	LMGENL_ATTR_REMOTEV4ADDR,

	LMGENL_ATTR_STS_STATUS,

	LMGENL_ATTR_PADQ_RLQ,
	LMGENL_ATTR_PADQ_RESOURCE,
	LMGENL_ATTR_PADQ_LATENCY,
	LMGENL_ATTR_PADQ_CDR,
	LMGENL_ATTR_PADQ_MDR,
	LMGENL_ATTR_PADQ_RESERVED1,
	LMGENL_ATTR_PADQ_RESERVED2,

	__LMGENL_ATTR_MAX,
};
#define LMGENL_ATTR_MAX (__LMGENL_ATTR_MAX - 1)

enum lmgenl_status
{
	LM_STATUS_DOWN = 0,
	LM_STATUS_UP,
};

#define LMGENL_VERSION 1
#define LMGENL_FAMILY_NAME "linkmetrics"
#define LMGENL_MCGROUP_NAME "lm_mc_group"

#endif	/* _LMGENL_H_ */
